spring:
    application:
        name: categories-service
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5436/categories-db
        username: postgres
        password: 123
    security:
     oauth2:
         resourceserver:
             jwt:
                 issuer-uri: http://localhost:8080/realms/rest-api
eureka:
    client:
        service-url:
            defaultZone: http://34.126.135.232:8761/eureka/
server:
    port: 8086