spring:
    application:
        name: categories-service
    profiles:
      active: dev
    config:
        import: optional:configserver:http://34.126.135.232:8888
server:
    port: 8083
springdoc:
  api-docs:
    path: /v3/api-docs
